/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package room.service;

import javax.net.ssl.SSLSocketFactory;
import javax.security.auth.callback.Callback;

import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

public class App {

    public static void main(String[] args) throws MqttException {
        MqttClient client = new MqttClient("tcp://broker.mqtt-dashboard.com:1883", MqttClient.generateClientId(), new MemoryPersistence());
        MqttConnectOptions mqttConnectOptions = new MqttConnectOptions();
        mqttConnectOptions.setUserName("panini");
        mqttConnectOptions.setPassword("eleeleele".toCharArray());
        client.connect(mqttConnectOptions);
        
        client.setCallback(new MqttCallback() {
			
			@Override
			public void messageArrived(String topic, MqttMessage message) throws Exception {
				System.out.println(topic);
				System.out.println(message);
			}
			
			@Override
			public void deliveryComplete(IMqttDeliveryToken token) {
			}
			
			@Override
			public void connectionLost(Throwable cause) {
			}
  
        });
        
        client.subscribe("esp32/light");
        client.subscribe("esp32/motion");
        client.disconnect();
    }
}
