/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package room.service;

import room.service.html.DataService;
import room.service.mqtt.MQTTServer;

import room.service.serial.*;
import room.service.utils.JsonUtils;

import io.vertx.core.Vertx;

public class App {

	public static void main(String[] args) throws Exception {
		// Create a blocking queue to store the received messages
		CommChannel serial = new SerialCommChannel("/dev/ttyACM0", 9600);
		Vertx vertx = Vertx.vertx();
		DataService service = new DataService(8080);
		vertx.deployVerticle(service);
		Thread serverThread = new Thread(() -> {
			new MQTTServer(serial);
		});
		Thread.sleep(5000);
		Thread readThread = new Thread(() -> {
			while (true) {
				if (serial.isMsgAvailable()) {
					try {
						String msg = serial.receiveMsg();
						System.out.println(msg);
						if (JsonUtils.isFromArduino(msg)) {
							service.addMeasure(JsonUtils.getJsonWithTimestamp(msg));
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		});
		Thread.sleep(5000);
	
		
		serverThread.start();
		readThread.start();
	}

}
